[project]
name = "idc409-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "imutils>=0.5.4",
    "marimo>=0.17.0",
    "matplotlib>=3.10.7",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.3",
]
